nyanlang : {
    "hello/hi" : "nyanayn",
    "pain" : "ouchy-nyaouchy",
    "angry" : "hiss",
    "hate" : "hiss",
    "hungry" : "wrrrao",
    "happy" : "purr",
    "you" : "nyu",
    "small" : "tinyi",
    "cute" : "kanyaii",
    "kill" : "scratch nya~",
    "cat" : "nekyon",
    "fight" : "battle of the nya~",
    "no" : "nyo",
    "not" : "mewot",
    "y'all" : "ny'all",
    "the" : "nye",
    "okay" : "oki-doki",
    "ok" : "oki-doki",
    "catgirl" : "nekyongurl",
    "catboy" : "nekyonboi",
    "girl" : "gurl",
    "now" : "maow",
    "good night" : "Nyaight~ Nyaight~",
    "huh" : "nyaa nyaa~",
    "stupid" : "snyupid",
    "sorry" : "sowwy~",
    "kid": "kittyen",
    "child" : "kittyen",
    "children" : "kittyens",
    "please" : "pwease",
    "what" : "meowhat",
    "war" : "nyar~",
    "mistress" : "meowstress",
    "master" : "meowster",
    "mother" : "meowther",
    "mama" : "meowameowa",
    "enough" : "enyagh",
    "can" : "nyan",
    "can't" : "nyan't",
    "year" : "nyear nyof nye nekyons",
    "month" : "meownth",
    "day" : "nayn",
    "night" : "nyight",
    "chips" : "nyips",
    "crisps" : "nyips",
    "die" : "nyie",
    "dying" : "nying",
    "died" : "nyied",
    "perfect" : "nyerfect",
    "perfection" : "nyerfection",
    "!" : "meow~!",
    "?" : "nya~?",
}
def nyan_translate(message):
    user_input = message
    output = ""
    for c in user_input:
        nyan_char = nyanlang.get(c.lower())
        output = output + nyan_char
    return output